// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto
	pvp_service.proto

It has these top-level messages:
	C2S_ConnectMsg
	S2C_ConnectMsg
	C2S_JoinRoomMsg
	S2C_JoinRoomMsg
	C2S_ProgressMsg
	S2C_ProgressMsg
	S2C_ReadyMsg
	C2S_InputSkillMsg
	InputData
	FrameData
	S2C_FrameMsg
	CreatePVPRequest
	CreatePVPResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ID int32

const (
	ID_MSG_BEGIN      ID = 0
	ID_C2S_Connect    ID = 1
	ID_S2C_Connect    ID = 1
	ID_C2S_Heartbeat  ID = 2
	ID_S2C_Heartbeat  ID = 2
	ID_C2S_JoinRoom   ID = 10
	ID_S2C_JoinRoom   ID = 10
	ID_C2S_Progress   ID = 20
	ID_S2C_Progress   ID = 20
	ID_C2S_Ready      ID = 30
	ID_S2C_Ready      ID = 30
	ID_S2C_Frame      ID = 40
	ID_C2S_InputSkill ID = 50
	ID_S2C_InputSkill ID = 50
	ID_C2S_Result     ID = 100
	ID_S2C_Result     ID = 100
	ID_MSG_END        ID = 255
)

var ID_name = map[int32]string{
	0: "MSG_BEGIN",
	1: "C2S_Connect",
	// Duplicate value: 1: "S2C_Connect",
	2: "C2S_Heartbeat",
	// Duplicate value: 2: "S2C_Heartbeat",
	10: "C2S_JoinRoom",
	// Duplicate value: 10: "S2C_JoinRoom",
	20: "C2S_Progress",
	// Duplicate value: 20: "S2C_Progress",
	30: "C2S_Ready",
	// Duplicate value: 30: "S2C_Ready",
	40: "S2C_Frame",
	50: "C2S_InputSkill",
	// Duplicate value: 50: "S2C_InputSkill",
	100: "C2S_Result",
	// Duplicate value: 100: "S2C_Result",
	255: "MSG_END",
}
var ID_value = map[string]int32{
	"MSG_BEGIN":      0,
	"C2S_Connect":    1,
	"S2C_Connect":    1,
	"C2S_Heartbeat":  2,
	"S2C_Heartbeat":  2,
	"C2S_JoinRoom":   10,
	"S2C_JoinRoom":   10,
	"C2S_Progress":   20,
	"S2C_Progress":   20,
	"C2S_Ready":      30,
	"S2C_Ready":      30,
	"S2C_Frame":      40,
	"C2S_InputSkill": 50,
	"S2C_InputSkill": 50,
	"C2S_Result":     100,
	"S2C_Result":     100,
	"MSG_END":        255,
}

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}
func (x ID) String() string {
	return proto.EnumName(ID_name, int32(x))
}
func (x *ID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ID_value, data, "ID")
	if err != nil {
		return err
	}
	*x = ID(value)
	return nil
}
func (ID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type C2S_ConnectMsg struct {
	Token            *string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S_ConnectMsg) Reset()                    { *m = C2S_ConnectMsg{} }
func (m *C2S_ConnectMsg) String() string            { return proto.CompactTextString(m) }
func (*C2S_ConnectMsg) ProtoMessage()               {}
func (*C2S_ConnectMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S_ConnectMsg) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type S2C_ConnectMsg struct {
	ErrorCode        *int32 `protobuf:"varint,1,opt,name=errorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_ConnectMsg) Reset()                    { *m = S2C_ConnectMsg{} }
func (m *S2C_ConnectMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_ConnectMsg) ProtoMessage()               {}
func (*S2C_ConnectMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2C_ConnectMsg) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

type C2S_JoinRoomMsg struct {
	Room             *int32 `protobuf:"varint,1,opt,name=room" json:"room,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_JoinRoomMsg) Reset()                    { *m = C2S_JoinRoomMsg{} }
func (m *C2S_JoinRoomMsg) String() string            { return proto.CompactTextString(m) }
func (*C2S_JoinRoomMsg) ProtoMessage()               {}
func (*C2S_JoinRoomMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *C2S_JoinRoomMsg) GetRoom() int32 {
	if m != nil && m.Room != nil {
		return *m.Room
	}
	return 0
}

type S2C_JoinRoomMsg struct {
	Id               *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Others           []uint64 `protobuf:"varint,2,rep,name=others" json:"others,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *S2C_JoinRoomMsg) Reset()                    { *m = S2C_JoinRoomMsg{} }
func (m *S2C_JoinRoomMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_JoinRoomMsg) ProtoMessage()               {}
func (*S2C_JoinRoomMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *S2C_JoinRoomMsg) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *S2C_JoinRoomMsg) GetOthers() []uint64 {
	if m != nil {
		return m.Others
	}
	return nil
}

type C2S_ProgressMsg struct {
	Pro              *int32 `protobuf:"varint,1,opt,name=pro" json:"pro,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_ProgressMsg) Reset()                    { *m = C2S_ProgressMsg{} }
func (m *C2S_ProgressMsg) String() string            { return proto.CompactTextString(m) }
func (*C2S_ProgressMsg) ProtoMessage()               {}
func (*C2S_ProgressMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *C2S_ProgressMsg) GetPro() int32 {
	if m != nil && m.Pro != nil {
		return *m.Pro
	}
	return 0
}

type S2C_ProgressMsg struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pro              *int32  `protobuf:"varint,2,opt,name=pro" json:"pro,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2C_ProgressMsg) Reset()                    { *m = S2C_ProgressMsg{} }
func (m *S2C_ProgressMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_ProgressMsg) ProtoMessage()               {}
func (*S2C_ProgressMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *S2C_ProgressMsg) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *S2C_ProgressMsg) GetPro() int32 {
	if m != nil && m.Pro != nil {
		return *m.Pro
	}
	return 0
}

type S2C_ReadyMsg struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2C_ReadyMsg) Reset()                    { *m = S2C_ReadyMsg{} }
func (m *S2C_ReadyMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_ReadyMsg) ProtoMessage()               {}
func (*S2C_ReadyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *S2C_ReadyMsg) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type C2S_InputSkillMsg struct {
	Sid              *int32 `protobuf:"varint,1,opt,name=sid" json:"sid,omitempty"`
	X                *int32 `protobuf:"varint,2,opt,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,3,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_InputSkillMsg) Reset()                    { *m = C2S_InputSkillMsg{} }
func (m *C2S_InputSkillMsg) String() string            { return proto.CompactTextString(m) }
func (*C2S_InputSkillMsg) ProtoMessage()               {}
func (*C2S_InputSkillMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *C2S_InputSkillMsg) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *C2S_InputSkillMsg) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *C2S_InputSkillMsg) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type InputData struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sid              *int32  `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	X                *int32  `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Y                *int32  `protobuf:"varint,4,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InputData) Reset()                    { *m = InputData{} }
func (m *InputData) String() string            { return proto.CompactTextString(m) }
func (*InputData) ProtoMessage()               {}
func (*InputData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *InputData) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *InputData) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *InputData) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *InputData) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type FrameData struct {
	FrameID          *uint32      `protobuf:"varint,1,opt,name=frameID" json:"frameID,omitempty"`
	Input            []*InputData `protobuf:"bytes,2,rep,name=input" json:"input,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *FrameData) Reset()                    { *m = FrameData{} }
func (m *FrameData) String() string            { return proto.CompactTextString(m) }
func (*FrameData) ProtoMessage()               {}
func (*FrameData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FrameData) GetFrameID() uint32 {
	if m != nil && m.FrameID != nil {
		return *m.FrameID
	}
	return 0
}

func (m *FrameData) GetInput() []*InputData {
	if m != nil {
		return m.Input
	}
	return nil
}

type S2C_FrameMsg struct {
	Frames           []*FrameData `protobuf:"bytes,1,rep,name=frames" json:"frames,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *S2C_FrameMsg) Reset()                    { *m = S2C_FrameMsg{} }
func (m *S2C_FrameMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_FrameMsg) ProtoMessage()               {}
func (*S2C_FrameMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *S2C_FrameMsg) GetFrames() []*FrameData {
	if m != nil {
		return m.Frames
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S_ConnectMsg)(nil), "pb.C2S_ConnectMsg")
	proto.RegisterType((*S2C_ConnectMsg)(nil), "pb.S2C_ConnectMsg")
	proto.RegisterType((*C2S_JoinRoomMsg)(nil), "pb.C2S_JoinRoomMsg")
	proto.RegisterType((*S2C_JoinRoomMsg)(nil), "pb.S2C_JoinRoomMsg")
	proto.RegisterType((*C2S_ProgressMsg)(nil), "pb.C2S_ProgressMsg")
	proto.RegisterType((*S2C_ProgressMsg)(nil), "pb.S2C_ProgressMsg")
	proto.RegisterType((*S2C_ReadyMsg)(nil), "pb.S2C_ReadyMsg")
	proto.RegisterType((*C2S_InputSkillMsg)(nil), "pb.C2S_InputSkillMsg")
	proto.RegisterType((*InputData)(nil), "pb.InputData")
	proto.RegisterType((*FrameData)(nil), "pb.FrameData")
	proto.RegisterType((*S2C_FrameMsg)(nil), "pb.S2C_FrameMsg")
	proto.RegisterEnum("pb.ID", ID_name, ID_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdd, 0x6a, 0xdb, 0x30,
	0x14, 0x9e, 0x95, 0xa4, 0xc5, 0xa7, 0x71, 0xaa, 0x8a, 0x32, 0xcc, 0x18, 0xa5, 0xa8, 0x74, 0x84,
	0x5d, 0xe4, 0x22, 0x63, 0x17, 0xbb, 0xdc, 0x92, 0xae, 0x73, 0xa1, 0x65, 0x28, 0x0f, 0x50, 0x9c,
	0x59, 0xcb, 0x4c, 0x13, 0xcb, 0x48, 0x2a, 0x34, 0xaf, 0xb4, 0x97, 0xdc, 0x38, 0x92, 0x12, 0xab,
	0xa5, 0x77, 0xfa, 0x3e, 0x7f, 0x3f, 0xfa, 0x39, 0x86, 0x6c, 0x23, 0x8d, 0x29, 0x57, 0x72, 0xd2,
	0x6a, 0x65, 0x15, 0x23, 0xed, 0x92, 0x7f, 0x80, 0xd1, 0x6c, 0xba, 0xb8, 0x9f, 0xa9, 0xa6, 0x91,
	0xbf, 0xec, 0xad, 0x59, 0xb1, 0x53, 0x18, 0x58, 0xf5, 0x20, 0x9b, 0x3c, 0x39, 0x4f, 0xc6, 0xa9,
	0xf0, 0x80, 0x4f, 0x60, 0xb4, 0x98, 0xce, 0x62, 0xdd, 0x7b, 0x48, 0xa5, 0xd6, 0x4a, 0xcf, 0x54,
	0x25, 0x9d, 0x76, 0x20, 0x3a, 0x82, 0x5f, 0xc2, 0x31, 0xe6, 0xde, 0xa8, 0xba, 0x11, 0x4a, 0x6d,
	0xd0, 0xc0, 0xa0, 0xaf, 0x95, 0xda, 0x04, 0xad, 0x5b, 0xf3, 0x2f, 0x70, 0x8c, 0xb1, 0xb1, 0x6c,
	0x04, 0xa4, 0xae, 0x9c, 0xa8, 0x2f, 0x48, 0x5d, 0xb1, 0xb7, 0x70, 0xa0, 0xec, 0x1f, 0xa9, 0x4d,
	0x4e, 0xce, 0x7b, 0xe3, 0xbe, 0x08, 0x88, 0x5f, 0xf8, 0x86, 0x9f, 0x5a, 0xad, 0xb4, 0x34, 0x06,
	0xad, 0x14, 0x7a, 0xad, 0x56, 0xa1, 0x00, 0x97, 0xfc, 0x93, 0xcf, 0x8f, 0x45, 0x2f, 0xf3, 0x83,
	0x89, 0x74, 0xa6, 0x33, 0x18, 0xa2, 0x49, 0xc8, 0xb2, 0xda, 0xbe, 0xe2, 0xe0, 0x5f, 0xe1, 0x04,
	0x9b, 0x8b, 0xa6, 0x7d, 0xb4, 0x8b, 0x87, 0x7a, 0xbd, 0x0e, 0xdd, 0x26, 0xa8, 0x06, 0x02, 0x97,
	0x6c, 0x08, 0xc9, 0x53, 0x88, 0x4d, 0x9e, 0x10, 0x6d, 0xf3, 0x9e, 0x47, 0x5b, 0x5e, 0x40, 0xea,
	0xec, 0xf3, 0xd2, 0x96, 0xaf, 0xed, 0x08, 0xa3, 0xc8, 0x8b, 0xa8, 0xde, 0xb3, 0xa8, 0xfe, 0x2e,
	0xea, 0x06, 0xd2, 0xef, 0xba, 0xdc, 0x48, 0x17, 0x95, 0xc3, 0xe1, 0x6f, 0x04, 0xc5, 0xdc, 0xe5,
	0x65, 0x62, 0x07, 0xd9, 0x05, 0x0c, 0x6a, 0x6c, 0x74, 0xb7, 0x78, 0x34, 0xcd, 0x26, 0xed, 0x72,
	0xb2, 0xdf, 0x82, 0xf0, 0xdf, 0xf8, 0x67, 0x7f, 0x72, 0x97, 0x87, 0x87, 0xba, 0x84, 0x03, 0xe7,
	0x37, 0x79, 0xd2, 0xb9, 0xf6, 0x6d, 0x22, 0x7c, 0xfc, 0xf8, 0x97, 0x00, 0x29, 0xe6, 0x2c, 0x83,
	0xf4, 0x76, 0x71, 0x7d, 0xff, 0xed, 0xea, 0xba, 0xb8, 0xa3, 0x6f, 0xd8, 0x31, 0x1c, 0x45, 0xa3,
	0x45, 0x13, 0x24, 0xa2, 0x19, 0xa2, 0x09, 0x3b, 0x81, 0x0c, 0x15, 0x3f, 0x64, 0xa9, 0xed, 0x52,
	0x96, 0x96, 0x12, 0xa4, 0x50, 0x13, 0x53, 0x14, 0x86, 0xf1, 0x28, 0x51, 0x40, 0x26, 0x9e, 0x1a,
	0xcf, 0xc4, 0xc3, 0x40, 0x4f, 0x77, 0x9a, 0x88, 0xc9, 0x20, 0x45, 0x8d, 0x7b, 0x56, 0x7a, 0x86,
	0x70, 0xff, 0xca, 0x1d, 0x74, 0x87, 0xa3, 0x63, 0xc6, 0xfc, 0x7f, 0xd1, 0xbd, 0x31, 0x9d, 0x22,
	0x87, 0x92, 0x67, 0xdc, 0x08, 0xc0, 0x87, 0x9a, 0xc7, 0xb5, 0xa5, 0x15, 0x62, 0x9f, 0x1a, 0xf0,
	0x10, 0x0e, 0xf1, 0x4e, 0xae, 0xee, 0xe6, 0xf4, 0x5f, 0xf2, 0x8e, 0xd0, 0xe4, 0x7f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0x11, 0x7d, 0xad, 0x85, 0x03, 0x00, 0x00,
}
