// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	C2S_ConnectMsg
	S2C_ConnectMsg
	S2C_JoinRoomMsg
	S2C_StartMsg
	C2S_ProgressMsg
	S2C_ProgressMsg
	C2S_InputMsg
	InputData
	FrameData
	S2C_FrameMsg
	C2S_ResultMsg
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 消息ID
type ID int32

const (
	ID_MSG_BEGIN     ID = 0
	ID_MSG_Connect   ID = 1
	ID_MSG_Heartbeat ID = 2
	ID_MSG_JoinRoom  ID = 10
	ID_MSG_Progress  ID = 20
	ID_MSG_Ready     ID = 30
	ID_MSG_Start     ID = 40
	ID_MSG_Frame     ID = 50
	ID_MSG_Input     ID = 60
	ID_MSG_Result    ID = 70
	ID_MSG_Close     ID = 100
	ID_MSG_END       ID = 255
)

var ID_name = map[int32]string{
	0:   "MSG_BEGIN",
	1:   "MSG_Connect",
	2:   "MSG_Heartbeat",
	10:  "MSG_JoinRoom",
	20:  "MSG_Progress",
	30:  "MSG_Ready",
	40:  "MSG_Start",
	50:  "MSG_Frame",
	60:  "MSG_Input",
	70:  "MSG_Result",
	100: "MSG_Close",
	255: "MSG_END",
}
var ID_value = map[string]int32{
	"MSG_BEGIN":     0,
	"MSG_Connect":   1,
	"MSG_Heartbeat": 2,
	"MSG_JoinRoom":  10,
	"MSG_Progress":  20,
	"MSG_Ready":     30,
	"MSG_Start":     40,
	"MSG_Frame":     50,
	"MSG_Input":     60,
	"MSG_Result":    70,
	"MSG_Close":     100,
	"MSG_END":       255,
}

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}
func (x ID) String() string {
	return proto.EnumName(ID_name, int32(x))
}
func (x *ID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ID_value, data, "ID")
	if err != nil {
		return err
	}
	*x = ID(value)
	return nil
}
func (ID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 错误码
type ERRORCODE int32

const (
	ERRORCODE_ERR_Ok        ERRORCODE = 0
	ERRORCODE_ERR_NoPlayer  ERRORCODE = 1
	ERRORCODE_ERR_NoRoom    ERRORCODE = 2
	ERRORCODE_ERR_RoomState ERRORCODE = 3
	ERRORCODE_ERR_Token     ERRORCODE = 4
)

var ERRORCODE_name = map[int32]string{
	0: "ERR_Ok",
	1: "ERR_NoPlayer",
	2: "ERR_NoRoom",
	3: "ERR_RoomState",
	4: "ERR_Token",
}
var ERRORCODE_value = map[string]int32{
	"ERR_Ok":        0,
	"ERR_NoPlayer":  1,
	"ERR_NoRoom":    2,
	"ERR_RoomState": 3,
	"ERR_Token":     4,
}

func (x ERRORCODE) Enum() *ERRORCODE {
	p := new(ERRORCODE)
	*p = x
	return p
}
func (x ERRORCODE) String() string {
	return proto.EnumName(ERRORCODE_name, int32(x))
}
func (x *ERRORCODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ERRORCODE_value, data, "ERRORCODE")
	if err != nil {
		return err
	}
	*x = ERRORCODE(value)
	return nil
}
func (ERRORCODE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 客户端发来的第一个消息
type C2S_ConnectMsg struct {
	PlayerID         *uint64 `protobuf:"varint,1,opt,name=playerID" json:"playerID,omitempty"`
	BattleID         *uint64 `protobuf:"varint,2,opt,name=battleID" json:"battleID,omitempty"`
	Token            *string `protobuf:"bytes,10,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S_ConnectMsg) Reset()                    { *m = C2S_ConnectMsg{} }
func (m *C2S_ConnectMsg) String() string            { return proto.CompactTextString(m) }
func (*C2S_ConnectMsg) ProtoMessage()               {}
func (*C2S_ConnectMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S_ConnectMsg) GetPlayerID() uint64 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

func (m *C2S_ConnectMsg) GetBattleID() uint64 {
	if m != nil && m.BattleID != nil {
		return *m.BattleID
	}
	return 0
}

func (m *C2S_ConnectMsg) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// 服务端返回连接结果
type S2C_ConnectMsg struct {
	ErrorCode        *ERRORCODE `protobuf:"varint,1,opt,name=errorCode,enum=pb.ERRORCODE" json:"errorCode,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *S2C_ConnectMsg) Reset()                    { *m = S2C_ConnectMsg{} }
func (m *S2C_ConnectMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_ConnectMsg) ProtoMessage()               {}
func (*S2C_ConnectMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2C_ConnectMsg) GetErrorCode() ERRORCODE {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ERRORCODE_ERR_Ok
}

// 服务端返回进入房间消息
type S2C_JoinRoomMsg struct {
	Roomseatid       *int32   `protobuf:"varint,1,opt,name=roomseatid" json:"roomseatid,omitempty"`
	Others           []uint64 `protobuf:"varint,2,rep,name=others" json:"others,omitempty"`
	Pros             []int32  `protobuf:"varint,3,rep,name=pros" json:"pros,omitempty"`
	RandomSeed       *int32   `protobuf:"varint,4,opt,name=randomSeed" json:"randomSeed,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *S2C_JoinRoomMsg) Reset()                    { *m = S2C_JoinRoomMsg{} }
func (m *S2C_JoinRoomMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_JoinRoomMsg) ProtoMessage()               {}
func (*S2C_JoinRoomMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *S2C_JoinRoomMsg) GetRoomseatid() int32 {
	if m != nil && m.Roomseatid != nil {
		return *m.Roomseatid
	}
	return 0
}

func (m *S2C_JoinRoomMsg) GetOthers() []uint64 {
	if m != nil {
		return m.Others
	}
	return nil
}

func (m *S2C_JoinRoomMsg) GetPros() []int32 {
	if m != nil {
		return m.Pros
	}
	return nil
}

func (m *S2C_JoinRoomMsg) GetRandomSeed() int32 {
	if m != nil && m.RandomSeed != nil {
		return *m.RandomSeed
	}
	return 0
}

// 服务端广播开始游戏消息
type S2C_StartMsg struct {
	TimeStamp        *int64 `protobuf:"varint,1,opt,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C_StartMsg) Reset()                    { *m = S2C_StartMsg{} }
func (m *S2C_StartMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_StartMsg) ProtoMessage()               {}
func (*S2C_StartMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *S2C_StartMsg) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

// 读条进度
type C2S_ProgressMsg struct {
	Pro              *int32 `protobuf:"varint,1,opt,name=pro" json:"pro,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2S_ProgressMsg) Reset()                    { *m = C2S_ProgressMsg{} }
func (m *C2S_ProgressMsg) String() string            { return proto.CompactTextString(m) }
func (*C2S_ProgressMsg) ProtoMessage()               {}
func (*C2S_ProgressMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *C2S_ProgressMsg) GetPro() int32 {
	if m != nil && m.Pro != nil {
		return *m.Pro
	}
	return 0
}

// 读条进度
type S2C_ProgressMsg struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pro              *int32  `protobuf:"varint,2,opt,name=pro" json:"pro,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2C_ProgressMsg) Reset()                    { *m = S2C_ProgressMsg{} }
func (m *S2C_ProgressMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_ProgressMsg) ProtoMessage()               {}
func (*S2C_ProgressMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *S2C_ProgressMsg) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *S2C_ProgressMsg) GetPro() int32 {
	if m != nil && m.Pro != nil {
		return *m.Pro
	}
	return 0
}

// 操作输入消息
type C2S_InputMsg struct {
	Sid              *int32  `protobuf:"varint,1,opt,name=sid" json:"sid,omitempty"`
	X                *int32  `protobuf:"varint,2,opt,name=x" json:"x,omitempty"`
	Y                *int32  `protobuf:"varint,3,opt,name=y" json:"y,omitempty"`
	FrameID          *uint32 `protobuf:"varint,4,opt,name=frameID" json:"frameID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S_InputMsg) Reset()                    { *m = C2S_InputMsg{} }
func (m *C2S_InputMsg) String() string            { return proto.CompactTextString(m) }
func (*C2S_InputMsg) ProtoMessage()               {}
func (*C2S_InputMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *C2S_InputMsg) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *C2S_InputMsg) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *C2S_InputMsg) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *C2S_InputMsg) GetFrameID() uint32 {
	if m != nil && m.FrameID != nil {
		return *m.FrameID
	}
	return 0
}

// 帧存储操作输入
type InputData struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sid              *int32  `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	X                *int32  `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Y                *int32  `protobuf:"varint,4,opt,name=y" json:"y,omitempty"`
	Roomseatid       *int32  `protobuf:"varint,5,opt,name=roomseatid" json:"roomseatid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InputData) Reset()                    { *m = InputData{} }
func (m *InputData) String() string            { return proto.CompactTextString(m) }
func (*InputData) ProtoMessage()               {}
func (*InputData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InputData) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *InputData) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *InputData) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *InputData) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *InputData) GetRoomseatid() int32 {
	if m != nil && m.Roomseatid != nil {
		return *m.Roomseatid
	}
	return 0
}

// 帧数据
type FrameData struct {
	FrameID          *uint32      `protobuf:"varint,1,opt,name=frameID" json:"frameID,omitempty"`
	Input            []*InputData `protobuf:"bytes,2,rep,name=input" json:"input,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *FrameData) Reset()                    { *m = FrameData{} }
func (m *FrameData) String() string            { return proto.CompactTextString(m) }
func (*FrameData) ProtoMessage()               {}
func (*FrameData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FrameData) GetFrameID() uint32 {
	if m != nil && m.FrameID != nil {
		return *m.FrameID
	}
	return 0
}

func (m *FrameData) GetInput() []*InputData {
	if m != nil {
		return m.Input
	}
	return nil
}

// 广播帧消息
type S2C_FrameMsg struct {
	Frames           []*FrameData `protobuf:"bytes,1,rep,name=frames" json:"frames,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *S2C_FrameMsg) Reset()                    { *m = S2C_FrameMsg{} }
func (m *S2C_FrameMsg) String() string            { return proto.CompactTextString(m) }
func (*S2C_FrameMsg) ProtoMessage()               {}
func (*S2C_FrameMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *S2C_FrameMsg) GetFrames() []*FrameData {
	if m != nil {
		return m.Frames
	}
	return nil
}

// 结果消息
type C2S_ResultMsg struct {
	WinnerID         *uint64 `protobuf:"varint,1,opt,name=winnerID" json:"winnerID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S_ResultMsg) Reset()                    { *m = C2S_ResultMsg{} }
func (m *C2S_ResultMsg) String() string            { return proto.CompactTextString(m) }
func (*C2S_ResultMsg) ProtoMessage()               {}
func (*C2S_ResultMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *C2S_ResultMsg) GetWinnerID() uint64 {
	if m != nil && m.WinnerID != nil {
		return *m.WinnerID
	}
	return 0
}

func init() {
	proto.RegisterType((*C2S_ConnectMsg)(nil), "pb.C2S_ConnectMsg")
	proto.RegisterType((*S2C_ConnectMsg)(nil), "pb.S2C_ConnectMsg")
	proto.RegisterType((*S2C_JoinRoomMsg)(nil), "pb.S2C_JoinRoomMsg")
	proto.RegisterType((*S2C_StartMsg)(nil), "pb.S2C_StartMsg")
	proto.RegisterType((*C2S_ProgressMsg)(nil), "pb.C2S_ProgressMsg")
	proto.RegisterType((*S2C_ProgressMsg)(nil), "pb.S2C_ProgressMsg")
	proto.RegisterType((*C2S_InputMsg)(nil), "pb.C2S_InputMsg")
	proto.RegisterType((*InputData)(nil), "pb.InputData")
	proto.RegisterType((*FrameData)(nil), "pb.FrameData")
	proto.RegisterType((*S2C_FrameMsg)(nil), "pb.S2C_FrameMsg")
	proto.RegisterType((*C2S_ResultMsg)(nil), "pb.C2S_ResultMsg")
	proto.RegisterEnum("pb.ID", ID_name, ID_value)
	proto.RegisterEnum("pb.ERRORCODE", ERRORCODE_name, ERRORCODE_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0x3e, 0xba, 0x91, 0xbb, 0xb6, 0x33, 0xd6, 0x84, 0x22, 0x84, 0xa6, 0x2a, 0x13, 0x52,
	0xb5, 0xa1, 0x3d, 0x14, 0xf1, 0x06, 0x2f, 0x34, 0xdd, 0xe8, 0xa4, 0x7d, 0xc8, 0x41, 0xbc, 0x20,
	0x31, 0xb9, 0xc4, 0x8c, 0x68, 0x4d, 0x1c, 0xd9, 0x9e, 0x58, 0x1f, 0xf8, 0x77, 0xfc, 0x2f, 0xd0,
	0x75, 0xe2, 0xb4, 0x9b, 0x78, 0xf3, 0xb9, 0x37, 0xf7, 0x9c, 0x73, 0x3f, 0x02, 0x83, 0x52, 0x68,
	0xcd, 0x6f, 0xc5, 0x49, 0xad, 0xa4, 0x91, 0xd4, 0xaf, 0x17, 0xc9, 0x37, 0x18, 0x4e, 0x27, 0xd9,
	0xcd, 0x54, 0x56, 0x95, 0xf8, 0x6e, 0x2e, 0xf4, 0x2d, 0x7d, 0x09, 0xcf, 0xea, 0x25, 0x5f, 0x09,
	0x35, 0x4f, 0x63, 0x6f, 0xe4, 0x8d, 0x43, 0xd6, 0x61, 0xcc, 0x2d, 0xb8, 0x31, 0x4b, 0x31, 0x4f,
	0x63, 0xbf, 0xc9, 0x39, 0x4c, 0xf7, 0xa1, 0x67, 0xe4, 0x9d, 0xa8, 0x62, 0x18, 0x79, 0xe3, 0x88,
	0x35, 0x20, 0xf9, 0x00, 0xc3, 0x6c, 0x32, 0xdd, 0xe4, 0x3f, 0x86, 0x48, 0x28, 0x25, 0xd5, 0x54,
	0xe6, 0xc2, 0x0a, 0x0c, 0x27, 0x83, 0x93, 0x7a, 0x71, 0x32, 0x63, 0xec, 0x8a, 0x4d, 0xaf, 0xd2,
	0x19, 0x5b, 0xe7, 0x93, 0xdf, 0xb0, 0x87, 0xe5, 0xe7, 0xb2, 0xa8, 0x98, 0x94, 0x25, 0xd6, 0x1f,
	0x00, 0x28, 0x29, 0x4b, 0x2d, 0xb8, 0x29, 0x72, 0x4b, 0xd0, 0x63, 0x1b, 0x11, 0xfa, 0x02, 0xb6,
	0xa5, 0xf9, 0x29, 0x94, 0x8e, 0xfd, 0x51, 0x30, 0x0e, 0x59, 0x8b, 0x28, 0x85, 0xb0, 0x56, 0x52,
	0xc7, 0xc1, 0x28, 0x18, 0xf7, 0x98, 0x7d, 0x5b, 0x2e, 0x5e, 0xe5, 0xb2, 0xcc, 0x84, 0xc8, 0xe3,
	0xb0, 0xe5, 0xea, 0x22, 0xc9, 0x1b, 0xe8, 0xa3, 0x7c, 0x66, 0xb8, 0xb2, 0xde, 0x5f, 0x41, 0x64,
	0x8a, 0x52, 0x64, 0x86, 0x97, 0xb5, 0x95, 0x0e, 0xd8, 0x3a, 0x90, 0x1c, 0xc2, 0x1e, 0xce, 0xf2,
	0x5a, 0xc9, 0x5b, 0x25, 0xb4, 0xc6, 0x02, 0x02, 0x41, 0xad, 0x64, 0xeb, 0x12, 0x9f, 0xc9, 0xdb,
	0xa6, 0xa3, 0xcd, 0x8f, 0x86, 0xe0, 0xb7, 0x9d, 0x84, 0xcc, 0x2f, 0x72, 0x57, 0xe4, 0xaf, 0x8b,
	0xbe, 0x40, 0x1f, 0x99, 0xe7, 0x55, 0x7d, 0x6f, 0x5a, 0x5a, 0xdd, 0x35, 0x8f, 0x4f, 0xda, 0x07,
	0xef, 0xa1, 0xad, 0xf0, 0x1e, 0x10, 0xad, 0xe2, 0xa0, 0x41, 0x2b, 0x1a, 0xc3, 0xce, 0x0f, 0xc5,
	0x4b, 0x5c, 0x1a, 0xb6, 0x38, 0x60, 0x0e, 0x26, 0x05, 0x44, 0x96, 0x33, 0xe5, 0x86, 0xff, 0xcf,
	0x06, 0x8a, 0xf8, 0x4f, 0x44, 0x82, 0x47, 0x22, 0xa1, 0x13, 0x79, 0xbc, 0x96, 0xde, 0xd3, 0xb5,
	0x24, 0xe7, 0x10, 0x9d, 0xa2, 0xaa, 0x95, 0xda, 0x70, 0xe4, 0x3d, 0x72, 0x44, 0x0f, 0xa1, 0x57,
	0xa0, 0x23, 0xbb, 0xbc, 0xdd, 0xe6, 0x32, 0x3a, 0x8b, 0xac, 0xc9, 0x25, 0xef, 0x9a, 0xb5, 0x58,
	0x3e, 0x1c, 0xc7, 0x6b, 0xd8, 0xb6, 0xf5, 0x3a, 0xf6, 0xd6, 0x55, 0x9d, 0x1a, 0x6b, 0x93, 0xc9,
	0x31, 0x0c, 0x70, 0x8a, 0x4c, 0xe8, 0xfb, 0xa5, 0x3b, 0xf5, 0x5f, 0x45, 0x55, 0x6d, 0x9e, 0xba,
	0xc3, 0x47, 0x7f, 0x3c, 0xf0, 0xe7, 0x29, 0x1d, 0x40, 0x74, 0x91, 0x9d, 0xdd, 0x7c, 0x9c, 0x9d,
	0xcd, 0x2f, 0xc9, 0x16, 0xdd, 0x83, 0x5d, 0x84, 0xed, 0x39, 0x13, 0x8f, 0x3e, 0x87, 0x01, 0x06,
	0x3e, 0x09, 0xae, 0xcc, 0x42, 0x70, 0x43, 0x7c, 0x4a, 0xa0, 0x8f, 0x21, 0x77, 0xb3, 0x04, 0x5c,
	0xc4, 0xed, 0x9c, 0xec, 0x3b, 0x5a, 0x26, 0x78, 0xbe, 0x22, 0x07, 0x0e, 0xda, 0x3b, 0x23, 0x63,
	0x07, 0x6d, 0x07, 0x64, 0xe2, 0xa0, 0x1d, 0x03, 0x79, 0x4f, 0x87, 0x00, 0x4d, 0x2d, 0xb6, 0x41,
	0x4e, 0x5d, 0x7a, 0xba, 0x94, 0x5a, 0x10, 0x5c, 0xd2, 0x0e, 0xc2, 0xd9, 0x65, 0x4a, 0xfe, 0x7a,
	0x47, 0x5f, 0x21, 0xea, 0x7e, 0x2c, 0x0a, 0xb0, 0x3d, 0x63, 0xec, 0xe6, 0xea, 0x8e, 0x6c, 0xa1,
	0x27, 0x7c, 0x5f, 0xca, 0x6b, 0xfb, 0x73, 0x13, 0x0f, 0x79, 0x9b, 0x88, 0x75, 0xed, 0x63, 0x6b,
	0x88, 0x11, 0x65, 0x86, 0x1b, 0x41, 0x02, 0x94, 0xc2, 0xd0, 0x67, 0xfc, 0xb5, 0x49, 0xf8, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0x75, 0xbf, 0xd7, 0x5d, 0x50, 0x04, 0x00, 0x00,
}
